### ISSUE TITLE
fork了你的这个repo,谢谢

### ISSUE THREAD

**Issue by jumbojing** [spiritLHL/jupyter_notebook_blogs#4]
????可以吗

**Comment by spiritLHL** [comment]
你fork甚至fork了我的博客文章，这样算剽窃文章了都

**Comment by spiritLHL** [comment]
> ????可以吗

而且你连我的广告链接都fork了。。。帮我打广告吗这是

**Comment by jumbojing** [comment]
本身小白...别生气,我们可以做朋友呀,不同意呢,我就撤下来

**Comment by spiritLHL** [comment]
> 本身小白...别生气，我们可以做朋友呀，不同意呢，我就撤下来

你删掉我的文章就行了，在_posts文件夹里的文件，_nsotebooks文件夹里的文件，_words文件夹里的文件，有什么博客文章请自己写吧
